[package]
name = "mimalloc"
version = "0.1.22"
authors = [
    "Octavian Oncescu <octavonce@gmail.com>",
    "Vincent Rouillé <vincent@speedy37.fr>",
    "Thom Chiovoloni <chiovolonit@gmail.com>",
]
edition = "2018"
repository = "https://github.com/purpleprotocol/mimalloc_rust"
keywords = ["mimalloc", "allocator", "encrypted-heap", "performance"]
categories = ["memory-management", "api-bindings"]
description = "Performance and security oriented drop-in allocator"
license = "MIT"
readme = "README.md"

[workspace]
members = ["libmimalloc-sys", "libmimalloc-sys/sys-test"]

[badges]
travis-ci = { repository = "purpleprotocol/mimalloc_rust" }

[dependencies]
libmimalloc-sys = { path = "libmimalloc-sys", version = "0.1.18", default-features = false }

[features]
default = ["secure"]
secure = ["libmimalloc-sys/secure"]
unsafe_override_libc_allocators = ["libmimalloc-sys/unsafe_override_libc_allocators"]
local_dynamic_tls = ["libmimalloc-sys/local_dynamic_tls"]
